"""competitions nested categories teams pms

Revision ID: 084dc38c8dbb
Revises: bfa1a3db74a0
Create Date: 2026-07-15 06:12:05.002313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '084dc38c8dbb'
down_revision: Union[str, None] = 'bfa1a3db74a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NAMING_CONVENTION = {
    "fk": "fk_%(table_name)s_%(column_0_name)s",
    "ix": "ix_%(table_name)s_%(column_0_name)s",
}
FK_CAT_COMP = "fk_competition_categories_competition_id"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition_pms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'user_id')
    )
    with op.batch_alter_table('competition_pms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competition_pms_competition_id'), ['competition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competition_pms_user_id'), ['user_id'], unique=False)

    op.create_table('competition_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['competition_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competition_teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competition_teams_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competition_teams_lead_id'), ['lead_id'], unique=False)

    op.create_table('competition_team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['competition_teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id')
    )
    with op.batch_alter_table('competition_team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competition_team_members_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competition_team_members_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('competition_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competition_members_competition_id'))
        batch_op.drop_index(batch_op.f('ix_competition_members_user_id'))

    op.drop_table('competition_members')
    with op.batch_alter_table(
        'competition_categories', schema=None, naming_convention=NAMING_CONVENTION
    ) as batch_op:
        batch_op.add_column(sa.Column('competition_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_competition_categories_name'))
        batch_op.create_index(batch_op.f('ix_competition_categories_competition_id'), ['competition_id'], unique=False)
        batch_op.create_foreign_key(FK_CAT_COMP, 'competitions', ['competition_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('created_at')

    with op.batch_alter_table(
        'competitions', schema=None, naming_convention=NAMING_CONVENTION
    ) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_competitions_category_id'))
        batch_op.drop_index(batch_op.f('ix_competitions_team_lead_id'))
        batch_op.drop_constraint(batch_op.f('fk_competitions_category_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_competitions_team_lead_id'), type_='foreignkey')
        batch_op.drop_column('notes')
        batch_op.drop_column('team_name')
        batch_op.drop_column('category_id')
        batch_op.drop_column('team_lead_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        'competitions', schema=None, naming_convention=NAMING_CONVENTION
    ) as batch_op:
        batch_op.add_column(sa.Column('team_lead_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('team_name', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.create_foreign_key('fk_competitions_team_lead_id', 'users', ['team_lead_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_competitions_category_id', 'competition_categories', ['category_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_competitions_team_lead_id'), ['team_lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitions_category_id'), ['category_id'], unique=False)
        batch_op.drop_column('description')

    with op.batch_alter_table(
        'competition_categories', schema=None, naming_convention=NAMING_CONVENTION
    ) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(FK_CAT_COMP, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_competition_categories_competition_id'))
        batch_op.create_index(batch_op.f('ix_competition_categories_name'), ['name'], unique=1)
        batch_op.drop_column('competition_id')

    op.create_table('competition_members',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('competition_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'user_id')
    )
    with op.batch_alter_table('competition_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competition_members_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competition_members_competition_id'), ['competition_id'], unique=False)

    with op.batch_alter_table('competition_team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competition_team_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_competition_team_members_team_id'))

    op.drop_table('competition_team_members')
    with op.batch_alter_table('competition_teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competition_teams_lead_id'))
        batch_op.drop_index(batch_op.f('ix_competition_teams_category_id'))

    op.drop_table('competition_teams')
    with op.batch_alter_table('competition_pms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competition_pms_user_id'))
        batch_op.drop_index(batch_op.f('ix_competition_pms_competition_id'))

    op.drop_table('competition_pms')
    # ### end Alembic commands ###
