"""attach an inventory item to work requests

Revision ID: 33a5cef5b94f
Revises: e82bf7fc901f
Create Date: 2026-07-15 11:59:56.454211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '33a5cef5b94f'
down_revision: Union[str, None] = 'e82bf7fc901f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NAMING_CONVENTION = {
    "fk": "fk_%(table_name)s_%(column_0_name)s",
    "ix": "ix_%(table_name)s_%(column_0_name)s",
}
FK_ITEM = "fk_work_requests_item_id"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        'work_requests', schema=None, naming_convention=NAMING_CONVENTION
    ) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_work_requests_item_id'), ['item_id'], unique=False)
        batch_op.create_foreign_key(FK_ITEM, 'inventory_items', ['item_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        'work_requests', schema=None, naming_convention=NAMING_CONVENTION
    ) as batch_op:
        batch_op.drop_constraint(FK_ITEM, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_work_requests_item_id'))
        batch_op.drop_column('quantity')
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###
