"""sheets sync and rebuild tracking

Revision ID: 34cee6fe49db
Revises: a037e0d4ccc2
Create Date: 2026-07-15 21:03:13.346344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '34cee6fe49db'
down_revision: Union[str, None] = 'a037e0d4ccc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sheet_exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tab', sa.String(length=50), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('is_dirty', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sheet_exports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sheet_exports_tab'), ['tab'], unique=True)

    op.create_table('rebuild_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('spreadsheet_id', sa.String(length=255), nullable=False),
    sa.Column('tab_counts', sa.Text(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=False),
    sa.Column('snapshot_path', sa.String(length=500), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rebuild_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rebuild_batches_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rebuild_batches_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rebuild_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rebuild_batches_status'))
        batch_op.drop_index(batch_op.f('ix_rebuild_batches_actor_id'))

    op.drop_table('rebuild_batches')
    with op.batch_alter_table('sheet_exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sheet_exports_tab'))

    op.drop_table('sheet_exports')
    # ### end Alembic commands ###
