"""add inventory

Revision ID: 3aa1c45b3a9c
Revises: b0e9590a6809
Create Date: 2026-07-14 08:57:44.104816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3aa1c45b3a9c'
down_revision: Union[str, None] = 'b0e9590a6809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('asset_tag', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('team_lead_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_lead_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_items_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_team_lead_id'), ['team_lead_id'], unique=False)

    op.create_table('inventory_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('holder_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['holder_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_allocations_holder_id'), ['holder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_allocations_item_id'), ['item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_allocations_item_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_allocations_holder_id'))

    op.drop_table('inventory_allocations')
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_items_team_lead_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_name'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_category'))

    op.drop_table('inventory_items')
    # ### end Alembic commands ###
