"""task blocked state, comments, batch assignment

Revision ID: 689a99d163d0
Revises: 34cee6fe49db
Create Date: 2026-07-15 22:01:51.661523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '689a99d163d0'
down_revision: Union[str, None] = '34cee6fe49db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_comments_task_id'), ['task_id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_blocked', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(
            sa.Column('blocked_reason', sa.Text(), nullable=False, server_default='')
        )
        batch_op.add_column(sa.Column('batch_id', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_batch_id'), ['batch_id'], unique=False)

    # existing rows are backfilled by the server_default above; drop it so
    # future inserts rely on the ORM-side default instead (matches the rest
    # of the schema, where defaults live in the model, not the DB).
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('is_blocked', server_default=None)
        batch_op.alter_column('blocked_reason', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_batch_id'))
        batch_op.drop_column('batch_id')
        batch_op.drop_column('blocked_reason')
        batch_op.drop_column('is_blocked')

    with op.batch_alter_table('task_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_comments_task_id'))

    op.drop_table('task_comments')
    # ### end Alembic commands ###
