"""inventory locations and movement ledger

Revision ID: 7d6297d416f8
Revises: 084dc38c8dbb
Create Date: 2026-07-15 10:40:36.220656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7d6297d416f8'
down_revision: Union[str, None] = '084dc38c8dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# inventory_items has an existing unnamed FK (team_lead_id) that the SQLite batch
# recreate must reproduce with a name.
NAMING_CONVENTION = {
    "fk": "fk_%(table_name)s_%(column_0_name)s",
    "ix": "ix_%(table_name)s_%(column_0_name)s",
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_locations_name'), ['name'], unique=False)

    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=True),
    sa.Column('from_holder_id', sa.Integer(), nullable=True),
    sa.Column('to_location_id', sa.Integer(), nullable=True),
    sa.Column('to_holder_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_holder_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_location_id'], ['inventory_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_holder_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_location_id'], ['inventory_locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_movements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_request_id'), ['request_id'], unique=False)

    with op.batch_alter_table(
        'inventory_items', schema=None, naming_convention=NAMING_CONVENTION
    ) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('low_stock_threshold', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_inventory_items_sku'), ['sku'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        'inventory_items', schema=None, naming_convention=NAMING_CONVENTION
    ) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_items_sku'))
        batch_op.drop_column('low_stock_threshold')
        batch_op.drop_column('sku')

    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_movements_request_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_item_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_created_at'))

    op.drop_table('inventory_movements')
    with op.batch_alter_table('inventory_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_locations_name'))

    op.drop_table('inventory_locations')
    # ### end Alembic commands ###
