"""google account linking

Revision ID: a037e0d4ccc2
Revises: 0ba961ff527d
Create Date: 2026-07-15 20:37:35.802517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a037e0d4ccc2'
down_revision: Union[str, None] = '0ba961ff527d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_linked_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('google_linked_at')

    # ### end Alembic commands ###
