"""positions org tree

Revision ID: bfa1a3db74a0
Revises: f09de2fc7bf1
Create Date: 2026-07-15 05:52:39.831035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bfa1a3db74a0'
down_revision: Union[str, None] = 'f09de2fc7bf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_audit_log_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_audit_log_created_at'), ['created_at'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('occupant_id', sa.Integer(), nullable=True),
    sa.Column('is_technical', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['occupant_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['positions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_occupant_id'), ['occupant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_parent_id'), ['parent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_parent_id'))
        batch_op.drop_index(batch_op.f('ix_positions_occupant_id'))

    op.drop_table('positions')
    with op.batch_alter_table('org_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_org_audit_log_actor_id'))

    op.drop_table('org_audit_log')
    # ### end Alembic commands ###
