"""inventory checkout requests

Revision ID: e82bf7fc901f
Revises: 7d6297d416f8
Create Date: 2026-07-15 11:13:05.888732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e82bf7fc901f'
down_revision: Union[str, None] = '7d6297d416f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NAMING_CONVENTION = {
    "fk": "fk_%(table_name)s_%(column_0_name)s",
    "ix": "ix_%(table_name)s_%(column_0_name)s",
}
FK_MOVEMENT_REQUEST = "fk_inventory_movements_request_id"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('needed_by', sa.Date(), nullable=True),
    sa.Column('return_by', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_requests_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_requests_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_requests_status'), ['status'], unique=False)

    with op.batch_alter_table(
        'inventory_movements', schema=None, naming_convention=NAMING_CONVENTION
    ) as batch_op:
        batch_op.create_foreign_key(
            FK_MOVEMENT_REQUEST, 'inventory_requests', ['request_id'], ['id'], ondelete='SET NULL'
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        'inventory_movements', schema=None, naming_convention=NAMING_CONVENTION
    ) as batch_op:
        batch_op.drop_constraint(FK_MOVEMENT_REQUEST, type_='foreignkey')

    with op.batch_alter_table('inventory_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_requests_status'))
        batch_op.drop_index(batch_op.f('ix_inventory_requests_requester_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_requests_item_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_requests_created_at'))

    op.drop_table('inventory_requests')
    # ### end Alembic commands ###
