"""competition category team members single

Revision ID: f09de2fc7bf1
Revises: d0a0d393ed12
Create Date: 2026-07-15 01:31:37.461693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f09de2fc7bf1'
down_revision: Union[str, None] = 'd0a0d393ed12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Named constraints so the SQLite batch recreate of `competitions` succeeds.
NAMING_CONVENTION = {
    "fk": "fk_%(table_name)s_%(column_0_name)s",
    "ix": "ix_%(table_name)s_%(column_0_name)s",
}
FK_CATEGORY = "fk_competitions_category_id"
FK_TEAM_LEAD = "fk_competitions_team_lead_id"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competition_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competition_categories_name'), ['name'], unique=True)

    op.create_table('competition_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'user_id')
    )
    with op.batch_alter_table('competition_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competition_members_competition_id'), ['competition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competition_members_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table(
        'competitions', schema=None, naming_convention=NAMING_CONVENTION
    ) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('team_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('team_lead_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_competitions_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitions_team_lead_id'), ['team_lead_id'], unique=False)
        batch_op.create_foreign_key(
            FK_CATEGORY, 'competition_categories', ['category_id'], ['id'], ondelete='SET NULL'
        )
        batch_op.create_foreign_key(FK_TEAM_LEAD, 'users', ['team_lead_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('season')
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        'competitions', schema=None, naming_convention=NAMING_CONVENTION
    ) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('season', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(FK_TEAM_LEAD, type_='foreignkey')
        batch_op.drop_constraint(FK_CATEGORY, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_competitions_team_lead_id'))
        batch_op.drop_index(batch_op.f('ix_competitions_category_id'))
        batch_op.drop_column('team_lead_id')
        batch_op.drop_column('team_name')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('competition_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competition_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_competition_members_competition_id'))

    op.drop_table('competition_members')
    with op.batch_alter_table('competition_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competition_categories_name'))

    op.drop_table('competition_categories')
    # ### end Alembic commands ###
